# Generated by Django 5.2.13 on 2026-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usage', models.TextField()),
                ('side_effects', models.TextField()),
                ('dosage', models.CharField(max_length=255)),
            ],
        ),
    ]
